CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,

    CONSTRAINT chk_users_role
        CHECK (role IN ('USER', 'ADMIN'))
);


CREATE TABLE bookable_services
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(150) NOT NULL,
    description      TEXT,
    duration_minutes INTEGER      NOT NULL,
    active           BOOLEAN      NOT NULL,

    CONSTRAINT chk_bookable_services_duration
        CHECK (duration_minutes > 0)
);


CREATE TABLE bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                      NOT NULL,
    service_id BIGINT                      NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status     VARCHAR(20)                 NOT NULL,

    CONSTRAINT fk_bookings_user
        FOREIGN KEY (user_id)
            REFERENCES users (id),

    CONSTRAINT fk_bookings_service
        FOREIGN KEY (service_id)
            REFERENCES bookable_services (id),

    CONSTRAINT chk_bookings_time
        CHECK (end_time > start_time),

    CONSTRAINT chk_bookings_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED'))
);
